name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

env:
  PHP_CS_FIXER_IGNORE_ENV: 1

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 32
      matrix:
        os: [ ubuntu-latest ]
        php: [ "8.1", "8.2", "8.3" ]
        laravel: [10, 11]
        exclude:
          - php: 8.1
            laravel: 11
    name: PHP ${{ matrix.php }} Test on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, redis, pdo, pdo_mysql, bcmath
          tools: phpize
          coverage: none
      - name: Check PHP Version
        run: php -v
      - name: Check Composer Version
        run: composer -V
      - name: Check PHP Extensions
        run: php -m
      - name: Install Dependencies
        run: composer install --dev
      - name: Run Cs Fixer
        run: php ./vendor/bin/php-cs-fixer fix $1 --dry-run --diff --verbose --show-progress=dots
      - name: Run PHPStan
        run: php vendor/bin/phpstan analyse --memory-limit 300M -l 0 -c phpstan.neon ./src ./config
      - name: Run Test
        run: composer test
